
const $=q=>document.querySelector(q);
const fmt=(v,d=1)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('pt-PT',{minimumFractionDigits:d,maximumFractionDigits:d});
const COLORS=['#2f7d9e','#c55348','#668e6c','#bd8c2f','#7f6fa0'];
let data=null,view='anomalies';
async function getJson(u){const r=await fetch(u+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(r.status);return r.json()}
function tempBg(v){if(v==null)return'';v=Number(v);if(v<=-2)return'#8ebbd0';if(v<-.7)return'#c7dfe9';if(v<.7)return'#eef1df';if(v<2)return'#f1c8a7';return'#dc8073'}
function rainBg(v){if(v==null)return'';v=Number(v);if(v<50)return'#ead7a1';if(v<85)return'#f3e9c9';if(v<115)return'#e5eee6';if(v<160)return'#b7d9e5';return'#70aac2'}
function renderMatrix(){
 const mode=$('#ox-matrix-mode').value,years=[...new Set(data.monthly.map(r=>r.year))],months=[1,2,3,4,5,6,7,8,9,10,11,12],names=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];let s='<table><thead><tr><th>Ano</th>'+names.map(n=>`<th>${n}</th>`).join('')+'</tr></thead><tbody>';
 years.forEach(y=>{s+=`<tr><th>${y}</th>`;months.forEach(m=>{const r=data.monthly.find(x=>x.year===y&&x.month===m),valid=mode==='temp'?r?.temperature_valid:r?.precipitation_valid,val=mode==='temp'?r?.temp_anomaly:r?.precip_pct_normal;if(!r||!valid)s+='<td class="ox-cell invalid">—</td>';else s+=`<td class="ox-cell" title="${r.month_name} ${y}" style="background:${mode==='temp'?tempBg(val):rainBg(val)}">${mode==='temp'?`${val>=0?'+':''}${fmt(val,1)}°`:`${fmt(val,0)}%`}</td>`});s+='</tr>'});s+='</tbody></table>';$('#ox-matrix').innerHTML=s;
}
function lineChart(host,rows,key,unit,color='#2f7d9e'){
 const valid=rows.filter(r=>r[key]!=null),W=550,H=320,m={l:55,r:18,t:20,b:42};if(valid.length<2){host.innerHTML='<p>Dados insuficientes.</p>';return}
 const vals=valid.map(r=>Number(r[key])),mn=Math.min(...vals),mx=Math.max(...vals),pad=(mx-mn)*.12||1,ymin=mn-pad,ymax=mx+pad,x=i=>m.l+i/(valid.length-1)*(W-m.l-m.r),y=v=>m.t+(ymax-v)/(ymax-ymin)*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=ymin+(ymax-ymin)*i/4,yy=y(v);s+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,1)}</text>`}s+=`<path d="${valid.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(Number(r[key]))}`).join(' ')}" fill="none" stroke="${color}" stroke-width="2.6"/>`;valid.forEach((r,i)=>s+=`<circle cx="${x(i)}" cy="${y(Number(r[key]))}" r="3" fill="${color}"/><text x="${x(i)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.year}</text>`);s+=`<text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">${unit}</text></svg>`;host.innerHTML=s;
}
function renderAnnual(){lineChart($('#ox-annual-chart'),data.annual.filter(r=>r.temperature_valid),'tmean','°C');const t=data.trend||{};$('#ox-trend-note').textContent=`Declive descritivo nos anos completos: ${t.temperature_slope_c_per_year==null?'—':(t.temperature_slope_c_per_year>=0?'+':'')+fmt(t.temperature_slope_c_per_year,3)+' °C/ano'}. ${t.warning||''}`;}
function renderMonthProfile(){
 const rows=data.station_months||[],W=550,H=320,m={l:55,r:18,t:20,b:42},vals=rows.flatMap(r=>[r.station_tmean,r.normal_tmean]).filter(Number.isFinite),mn=Math.min(...vals)-1,mx=Math.max(...vals)+1,x=i=>m.l+i/11*(W-m.l-m.r),y=v=>m.t+(mx-v)/(mx-mn)*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=mn+(mx-mn)*i/4,yy=y(v);s+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,1)}</text>`}const path=k=>rows.filter(r=>r[k]!=null).map((r,i)=>`${i?'L':'M'} ${x(r.month-1)} ${y(Number(r[k]))}`).join(' ');s+=`<path d="${path('normal_tmean')}" fill="none" stroke="#8a999f" stroke-width="2" stroke-dasharray="5 4"/><path d="${path('station_tmean')}" fill="none" stroke="#2f7d9e" stroke-width="2.5"/>`;rows.forEach(r=>s+=`<text x="${x(r.month-1)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.month_name.slice(0,3)}</text>`);s+=`<text x="${m.l}" y="13" font-size="8" fill="#2f7d9e">● estação</text><text x="${m.l+70}" y="13" font-size="8" fill="#7f8e94">┄ normal 1991–2020</text></svg>`;$('#ox-month-profile').innerHTML=s;
}
function corrText(r){const a=Math.abs(Number(r));if(!Number.isFinite(a))return'Sem pares suficientes';const strength=a<.2?'muito fraca':a<.4?'fraca':a<.6?'moderada':a<.8?'forte':'muito forte';return `${strength} · ${r>0?'positiva':'negativa'}`}
function renderRelations(){
 const sel=$('#ox-relation');if(!sel.options.length){sel.innerHTML=data.correlations.map(x=>`<option value="${x.id}">${x.label}</option>`).join('');sel.onchange=renderRelations}
 const rel=data.correlations.find(x=>x.id===sel.value)||data.correlations[0];if(!rel)return;sel.value=rel.id;const pts=data.daily.filter(r=>r[rel.x]!=null&&r[rel.y]!=null),xs=pts.map(r=>Number(r[rel.x])),ys=pts.map(r=>Number(r[rel.y])),W=1100,H=430,m={l:70,r:20,t:20,b:50},xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),x=v=>m.l+(v-xmin)/(xmax-xmin||1)*(W-m.l-m.r),y=v=>m.t+(ymax-v)/(ymax-ymin||1)*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const xv=xmin+(xmax-xmin)*i/4,yv=ymin+(ymax-ymin)*i/4;s+=`<line x1="${m.l}" y1="${y(yv)}" x2="${W-m.r}" y2="${y(yv)}" stroke="#e7edef"/><text x="${m.l-7}" y="${y(yv)+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(yv,1)}</text><text x="${x(xv)}" y="${H-18}" text-anchor="middle" font-size="8" fill="#72828b">${fmt(xv,1)}</text>`}pts.forEach(p=>s+=`<circle cx="${x(Number(p[rel.x]))}" cy="${y(Number(p[rel.y]))}" r="2.5" fill="#2f7d9e" opacity=".42"><title>${p.date}</title></circle>`);s+=`<text x="${W/2}" y="${H-4}" text-anchor="middle" font-size="9" fill="#687a83">${rel.x_unit}</text><text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">${rel.y_unit}</text></svg>`;$('#ox-scatter').innerHTML=s;$('#ox-relation-stats').innerHTML=`<div class="ox-stat"><span>Correlação r</span><b>${fmt(rel.r,3)}</b></div><div class="ox-stat"><span>Leitura</span><b>${corrText(rel.r)}</b></div><div class="ox-stat"><span>Pares de dias</span><b>${pts.length}</b></div><div class="ox-stat"><span>Período</span><b>${data.series_start.slice(0,4)}–${data.series_end.slice(0,4)}</b></div>`;
}
function barChart(host,rows,key,label){
 const valid=rows.filter(r=>r[key]!=null),W=1100,H=350,m={l:55,r:20,t:20,b:42},mx=Math.max(1,...valid.map(r=>Number(r[key]))),bw=(W-m.l-m.r)/Math.max(1,valid.length)*.55,x=i=>m.l+(i+.5)/valid.length*(W-m.l-m.r),y=v=>m.t+(mx-v)/mx*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=mx*i/4,yy=y(v);s+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,0)}</text>`}valid.forEach((r,i)=>{const yy=y(Number(r[key]));s+=`<rect x="${x(i)-bw/2}" y="${yy}" width="${bw}" height="${H-m.b-yy}" rx="4" fill="#2f7d9e"/><text x="${x(i)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.year}${r.complete?'':'*'}</text>`});s+='</svg>';host.innerHTML=s;
}
function renderExtremes(){const key=$('#ox-index').value;barChart($('#ox-index-chart'),data.annual,key,key);$('#ox-index').onchange=renderExtremes}
function renderWind(){
 const rows=data.wind_sectors||[],W=550,H=330,cx=275,cy=165,R=125,mx=Math.max(1,...rows.map(r=>r.pct));let s=`<svg viewBox="0 0 ${W} ${H}">`;[.25,.5,.75,1].forEach(q=>s+=`<circle cx="${cx}" cy="${cy}" r="${R*q}" fill="none" stroke="#e2eaed"/>`);rows.forEach((r,i)=>{const a=(i*22.5-90)*Math.PI/180,len=R*r.pct/mx,x2=cx+Math.cos(a)*len,y2=cy+Math.sin(a)*len,lx=cx+Math.cos(a)*(R+15),ly=cy+Math.sin(a)*(R+15);s+=`<line x1="${cx}" y1="${cy}" x2="${x2}" y2="${y2}" stroke="#2f7d9e" stroke-width="8" stroke-linecap="round"/><text x="${lx}" y="${ly+3}" text-anchor="middle" font-size="8" fill="#647781">${r.direction}</text>`});s+='</svg>';$('#ox-wind-chart').innerHTML=s;const top=[...rows].sort((a,b)=>b.pct-a.pct).slice(0,3);$('#ox-wind-note').innerHTML=`<p>Esta distribuição usa a <strong>direção dominante de cada dia</strong>, portanto cada dia pesa uma vez. Os setores mais frequentes são ${top.map(x=>`${x.direction} (${fmt(x.pct,1)}%)`).join(', ')}.</p><p>Para frequência por amostras de 1/5 minutos, rajada média e rosa detalhada, use a análise de Vento da Climatologia.</p>`;
}
function renderQuality(){
 const q=data.quality||{},ys=data.quality_years||[];$('#ox-quality-stats').innerHTML=`<div class="ox-stat"><span>Dias válidos</span><b>${q.valid_days||0}</b></div><div class="ox-stat"><span>Dias em falta</span><b>${q.missing_day_count||0}</b></div><div class="ox-stat"><span>Linhas inválidas</span><b>${q.invalid_row_count||0}</b></div><div class="ox-stat"><span>Duplicados</span><b>${q.duplicate_count||0}</b></div>`;barChart($('#ox-quality-chart'),ys,'coverage_pct','Cobertura %');const m=data.methodology||{};$('#ox-method').innerHTML=`<p>${m.scope}</p><p><strong>Correlações:</strong> ${m.correlation}</p><p><strong>Vento:</strong> ${m.wind}</p><p><strong>Tendências:</strong> ${m.trend}</p>`;
}
function show(v){view=v;document.querySelectorAll('.ox-view').forEach(x=>x.hidden=x.id!==`ox-${v}`);document.querySelectorAll('#ox-nav button').forEach(b=>b.classList.toggle('is-active',b.dataset.view===v));if(v==='anomalies'){renderMatrix();renderAnnual();renderMonthProfile()}if(v==='relations')renderRelations();if(v==='extremes')renderExtremes();if(v==='wind')renderWind();if(v==='quality')renderQuality()}
async function init(){data=await getJson('observatory.json');$('#ox-series').textContent=`Série ${data.series_start} — ${data.series_end}`;document.querySelectorAll('#ox-nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#ox-matrix-mode').onchange=renderMatrix;show('anomalies')}
init();