
const $=q=>document.querySelector(q);
const fmt=(v,d=1)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('pt-PT',{minimumFractionDigits:d,maximumFractionDigits:d});
const COLORS=['#2f7d9e','#c55348','#668e6c','#bd8c2f','#7f6fa0'];
let data=null,skill=null,verification=null,localModel=null,view='anomalies';
async function getJson(u){const r=await fetch(u+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(r.status);return r.json()}
function tempBg(v){if(v==null)return'';v=Number(v);if(v<=-2)return'#8ebbd0';if(v<-.7)return'#c7dfe9';if(v<.7)return'#eef1df';if(v<2)return'#f1c8a7';return'#dc8073'}
function rainBg(v){if(v==null)return'';v=Number(v);if(v<50)return'#ead7a1';if(v<85)return'#f3e9c9';if(v<115)return'#e5eee6';if(v<160)return'#b7d9e5';return'#70aac2'}
function renderMatrix(){
 const mode=$('#ox-matrix-mode').value,years=[...new Set(data.monthly.map(r=>r.year))],months=[1,2,3,4,5,6,7,8,9,10,11,12],names=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];let s='<table><thead><tr><th>Ano</th>'+names.map(n=>`<th>${n}</th>`).join('')+'</tr></thead><tbody>';
 years.forEach(y=>{s+=`<tr><th>${y}</th>`;months.forEach(m=>{const r=data.monthly.find(x=>x.year===y&&x.month===m),valid=mode==='temp'?r?.temperature_valid:r?.precipitation_valid,val=mode==='temp'?r?.temp_anomaly:r?.precip_pct_normal;if(!r||!valid)s+='<td class="ox-cell invalid">—</td>';else s+=`<td class="ox-cell" title="${r.month_name} ${y}" style="background:${mode==='temp'?tempBg(val):rainBg(val)}">${mode==='temp'?`${val>=0?'+':''}${fmt(val,1)}°`:`${fmt(val,0)}%`}</td>`});s+='</tr>'});s+='</tbody></table>';$('#ox-matrix').innerHTML=s;
}
function lineChart(host,rows,key,unit,color='#2f7d9e'){
 const valid=rows.filter(r=>r[key]!=null),W=550,H=320,m={l:55,r:18,t:20,b:42};if(valid.length<2){host.innerHTML='<p>Dados insuficientes.</p>';return}
 const vals=valid.map(r=>Number(r[key])),mn=Math.min(...vals),mx=Math.max(...vals),pad=(mx-mn)*.12||1,ymin=mn-pad,ymax=mx+pad,x=i=>m.l+i/(valid.length-1)*(W-m.l-m.r),y=v=>m.t+(ymax-v)/(ymax-ymin)*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=ymin+(ymax-ymin)*i/4,yy=y(v);s+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,1)}</text>`}s+=`<path d="${valid.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(Number(r[key]))}`).join(' ')}" fill="none" stroke="${color}" stroke-width="2.6"/>`;valid.forEach((r,i)=>s+=`<circle cx="${x(i)}" cy="${y(Number(r[key]))}" r="4" fill="${color}"><title>${r.year}: ${fmt(r[key],1)} ${unit}</title></circle><text x="${x(i)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.year}</text>`);s+=`<text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">${unit}</text></svg>`;host.innerHTML=s;
}
function renderAnnual(){
 const mode=$('#ox-annual-mode')?.value||'temp',host=$('#ox-annual-chart'),t=data.trend||{};
 if(mode==='temp'){lineChart(host,data.annual.filter(r=>r.temperature_valid),'tmean','°C');$('#ox-trend-note').textContent=`Temperatura média anual. Declive descritivo nos anos completos: ${t.temperature_slope_c_per_year==null?'—':(t.temperature_slope_c_per_year>=0?'+':'')+fmt(t.temperature_slope_c_per_year,3)+' °C/ano'}. ${t.warning||''}`;return}
 const rows=(data.annual||[]).filter(r=>r.precip_mm!=null),W=550,H=320,m={l:60,r:18,t:22,b:42};if(!rows.length){host.innerHTML='<p>Sem totais anuais de precipitação.</p>';$('#ox-trend-note').textContent='';return}
 const vals=rows.map(r=>Number(r.precip_mm)),mx=Math.max(...vals)*1.12||1,x=i=>m.l+i/(Math.max(1,rows.length-1))*(W-m.l-m.r),y=v=>m.t+(mx-v)/mx*(H-m.t-m.b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=mx*i/4,yy=y(v);svg+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,0)}</text>`}svg+=`<path d="${rows.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(Number(r.precip_mm))}`).join(' ')}" fill="none" stroke="#397f98" stroke-width="2.5"/>`;rows.forEach((r,i)=>{const valid=r.precipitation_valid;svg+=`<circle cx="${x(i)}" cy="${y(Number(r.precip_mm))}" r="5" fill="${valid?'#397f98':'#fff'}" stroke="${valid?'#397f98':'#a98b47'}" stroke-width="2"><title>${r.year}: ${fmt(r.precip_mm,0)} mm · ${valid?'total válido':`total com ${r.missing_days||0} dia(s) em falta`}</title></circle><text x="${x(i)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.year}</text>`});svg+=`<text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">mm</text></svg>`;host.innerHTML=svg;$('#ox-trend-note').textContent=`Precipitação acumulada observada. Círculo vazio = total não climatologicamente válido por falhas. Declive só usa anos completos: ${t.precip_slope_mm_per_year==null?'—':(t.precip_slope_mm_per_year>=0?'+':'')+fmt(t.precip_slope_mm_per_year,1)+' mm/ano'}. ${t.warning||''}`;
}
function renderMonthProfile(){
 const mode=$('#ox-profile-mode')?.value||'temp',rows=data.station_months||[],host=$('#ox-month-profile'),note=$('#ox-profile-note'),W=550,H=320,m={l:58,r:18,t:22,b:42},sk=mode==='temp'?'station_tmean':'station_precip',nk=mode==='temp'?'normal_tmean':'normal_precip',unit=mode==='temp'?'°C':'mm',vals=rows.flatMap(r=>[r[sk],r[nk]]).filter(Number.isFinite);
 if(vals.length<2){host.innerHTML='<p>Dados insuficientes.</p>';note.textContent='';return}let mn=mode==='temp'?Math.min(...vals)-1:0,mx=mode==='temp'?Math.max(...vals)+1:Math.max(...vals)*1.12||1,x=i=>m.l+i/11*(W-m.l-m.r),y=v=>m.t+(mx-v)/(mx-mn||1)*(H-m.t-m.b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=mn+(mx-mn)*i/4,yy=y(v);svg+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,mode==='temp'?1:0)}</text>`}const line=k=>rows.filter(r=>r[k]!=null).map((r,j)=>`${j?'L':'M'} ${x(r.month-1)} ${y(Number(r[k]))}`).join(' ');svg+=`<path d="${line(nk)}" fill="none" stroke="#8a999f" stroke-width="2" stroke-dasharray="5 4"/><path d="${line(sk)}" fill="none" stroke="#2f7d9e" stroke-width="2.5"/>`;rows.forEach(r=>{const sv=r[sk],nv=r[nk],n=mode==='temp'?r.n_temp:r.n_precip;if(sv!=null)svg+=`<circle cx="${x(r.month-1)}" cy="${y(Number(sv))}" r="4" fill="#2f7d9e"><title>${r.month_name}: estação ${fmt(sv,mode==='temp'?1:0)} ${unit} · normal ${fmt(nv,mode==='temp'?1:0)} ${unit} · N=${n}</title></circle>`;svg+=`<text x="${x(r.month-1)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.month_name.slice(0,3)}</text>`});svg+=`<text x="${m.l}" y="14" font-size="8" fill="#2f7d9e">● estação</text><text x="${m.l+70}" y="14" font-size="8" fill="#7f8e94">┄ normal 1991–2020</text><text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">${unit}</text></svg>`;host.innerHTML=svg;note.textContent=mode==='temp'?'Média dos meses válidos da estação por mês do calendário.':'Média dos totais mensais completos da estação; meses com falhas não entram na referência local.';
}
function renderRelations(){
 const sel=$('#ox-relation');if(!sel.options.length){sel.innerHTML=data.correlations.map(x=>`<option value="${x.id}">${x.label}</option>`).join('');sel.onchange=renderRelations}
 const rel=data.correlations.find(x=>x.id===sel.value)||data.correlations[0];if(!rel)return;sel.value=rel.id;const pts=data.daily.filter(r=>r[rel.x]!=null&&r[rel.y]!=null),xs=pts.map(r=>Number(r[rel.x])),ys=pts.map(r=>Number(r[rel.y])),W=1100,H=430,m={l:70,r:20,t:20,b:50},xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),x=v=>m.l+(v-xmin)/(xmax-xmin||1)*(W-m.l-m.r),y=v=>m.t+(ymax-v)/(ymax-ymin||1)*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const xv=xmin+(xmax-xmin)*i/4,yv=ymin+(ymax-ymin)*i/4;s+=`<line x1="${m.l}" y1="${y(yv)}" x2="${W-m.r}" y2="${y(yv)}" stroke="#e7edef"/><text x="${m.l-7}" y="${y(yv)+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(yv,1)}</text><text x="${x(xv)}" y="${H-18}" text-anchor="middle" font-size="8" fill="#72828b">${fmt(xv,1)}</text>`}pts.forEach(p=>s+=`<circle cx="${x(Number(p[rel.x]))}" cy="${y(Number(p[rel.y]))}" r="2.5" fill="#2f7d9e" opacity=".42"><title>${p.date}</title></circle>`);s+=`<text x="${W/2}" y="${H-4}" text-anchor="middle" font-size="9" fill="#687a83">${rel.x_unit}</text><text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">${rel.y_unit}</text></svg>`;$('#ox-scatter').innerHTML=s;$('#ox-relation-stats').innerHTML=`<div class="ox-stat"><span>Correlação r</span><b>${fmt(rel.r,3)}</b></div><div class="ox-stat"><span>Leitura</span><b>${corrText(rel.r)}</b></div><div class="ox-stat"><span>Pares de dias</span><b>${pts.length}</b></div><div class="ox-stat"><span>Período</span><b>${data.series_start.slice(0,4)}–${data.series_end.slice(0,4)}</b></div>`;
}
function barChart(host,rows,key,label){
 const valid=rows.filter(r=>r[key]!=null),W=1100,H=350,m={l:55,r:20,t:20,b:42},mx=Math.max(1,...valid.map(r=>Number(r[key]))),bw=(W-m.l-m.r)/Math.max(1,valid.length)*.55,x=i=>m.l+(i+.5)/valid.length*(W-m.l-m.r),y=v=>m.t+(mx-v)/mx*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=mx*i/4,yy=y(v);s+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,0)}</text>`}valid.forEach((r,i)=>{const yy=y(Number(r[key]));s+=`<rect x="${x(i)-bw/2}" y="${yy}" width="${bw}" height="${H-m.b-yy}" rx="4" fill="#2f7d9e"><title>${r.year}: ${fmt(r[key],1)}</title></rect><text x="${x(i)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.year}${r.complete?'':'*'}</text>`});s+='</svg>';host.innerHTML=s;
}
function renderExtremes(){const key=$('#ox-index').value;barChart($('#ox-index-chart'),data.annual,key,key);$('#ox-index').onchange=renderExtremes}
let oxTip=null;function skillTip(ev,html){if(!oxTip){oxTip=document.createElement('div');oxTip.className='ox-skill-tooltip';document.body.appendChild(oxTip)}oxTip.innerHTML=html;oxTip.style.display='block';let x=ev.clientX+14,y=ev.clientY+14;if(x+oxTip.offsetWidth>innerWidth-10)x=ev.clientX-oxTip.offsetWidth-14;if(y+oxTip.offsetHeight>innerHeight-10)y=ev.clientY-oxTip.offsetHeight-14;oxTip.style.left=x+'px';oxTip.style.top=y+'px'}function hideSkillTip(){if(oxTip)oxTip.style.display='none'}
function skillUnit(v){return v==='precip'?'mm':'°C'}
function skillLabel(v){return {tmax:'T máxima',tmin:'T mínima',tmean:'T média',precip:'Precipitação'}[v]||v}
function skillMetricLabel(m){return {mae:'Erro absoluto médio',bias:'Viés',rmse:'RMSE'}[m]||m}

function modelEntries(){return Object.entries(skill?.models||{}).filter(([,m])=>m.available)}
function confidenceLabel(x){return x==='high'?'Alta':x==='moderate'?'Moderada':'Baixa'}
function localVarLabel(v){return {tmax:'T máxima',tmin:'T mínima',tmean:'T média',precip:'Precipitação'}[v]||v}
function renderLocalModel(){
 const status=$('#ox-local-status'),meta=$('#ox-local-meta'),host=$('#ox-local-current');if(!status||!host)return;
 if(!localModel?.available){status.textContent='A recolher histórico';status.className='ox-local-status is-low';meta.innerHTML='';host.innerHTML='<p class="ox-note">Ainda não existe amostra suficiente ou a calibração não pôde ser atualizada.</p>';renderLocalValidation();renderLocalScenarios();return}
 status.textContent=localModel.eligible_to_consider_promotion?'Experimental · desempenho promissor':'Experimental · em validação';status.className=`ox-local-status ${localModel.eligible_to_consider_promotion?'is-good':'is-medium'}`;
 const n=localModel.training_samples_by_lead?.['1']||0,imp=localModel.validation_mean_improvement_pct;
 meta.innerHTML=[['Modelo',localModel.model_id||'—'],['Treinado até',localModel.trained_through||'—'],['Casos D+1',n],['Melhoria média',imp==null?'—':`${imp>=0?'+':''}${fmt(imp,1)}%`]].map(x=>`<div class="ox-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');
 const variable=$('#ox-local-variable').value,leads=[1,2,3,5,7];host.innerHTML=leads.map(l=>{const r=localModel.current?.[String(l)],p=r?.[variable];if(!r||!p)return `<div class="ox-local-card"><span>D+${l}</span><b>—</b><small>sem previsão</small></div>`;if(variable==='precip'){return `<div class="ox-local-card"><span>D+${l} · ${r.date.slice(5)}</span><b>${fmt(p.probability_pct,0)}% chuva</b><strong>${fmt(p.expected_mm,1)} mm esperados</strong><small>se chover: ${fmt(p.conditional_range80_mm?.[0],1)}–${fmt(p.conditional_range80_mm?.[1],1)} mm · confiança ${confidenceLabel(p.confidence).toLowerCase()}</small><em>${r.scenario_label||''}</em></div>`}return `<div class="ox-local-card"><span>D+${l} · ${r.date.slice(5)}</span><b>${fmt(p.value,1)} °C</b><strong>${fmt(p.interval80?.[0],1)}–${fmt(p.interval80?.[1],1)} °C</strong><small>intervalo empírico ~80% · confiança ${confidenceLabel(p.confidence).toLowerCase()}</small><em>${r.scenario_label||''}</em></div>`}).join('');
 renderLocalValidation();renderLocalScenarios();
}
function renderLocalValidation(){const host=$('#ox-local-validation');if(!host)return;if(!localModel?.validation){host.innerHTML='<p>Sem validação disponível.</p>';return}const v=$('#ox-local-validation-var').value,leads=[1,2,3,5,7];host.innerHTML=leads.map(l=>{const x=localModel.validation?.[String(l)]?.variables?.[v];if(!x)return `<div class="ox-validation-row"><b>D+${l}</b><span>—</span></div>`;const imp=x.improvement_pct,cls=imp==null?'neutral':imp>=2?'good':imp>-2?'neutral':'bad',local=v==='precip'?x.local_mae_mm:x.local_mae,base=v==='precip'?x.best_match_mae_mm:x.best_match_mae,unit=v==='precip'?'mm':'°C';return `<div class="ox-validation-row"><b>D+${l}</b><div><span>Meteo Ranhados ${fmt(local,2)} ${unit}</span><small>Best Match ${fmt(base,2)} ${unit} · n=${x.samples||0}</small></div><strong class="${cls}">${imp==null?'—':`${imp>=0?'+':''}${fmt(imp,1)}%`}</strong></div>`}).join('')}
function renderLocalScenarios(){const host=$('#ox-local-scenarios');if(!host)return;const c=localModel?.scenario_counts||{},groups=[['Precipitação',['rain:dry','rain:trace','rain:rain','rain:wet']],['Nuvens',['cloud:clear','cloud:mixed','cloud:overcast']],['Vento',['wind:calm','wind:breezy','wind:windy']]],labels={'rain:dry':'Seco','rain:trace':'Incerto','rain:rain':'Chuva','rain:wet':'Chuva significativa','cloud:clear':'Pouco nublado','cloud:mixed':'Variável','cloud:overcast':'Muito nublado','wind:calm':'Fraco','wind:breezy':'Moderado','wind:windy':'Forte'};host.innerHTML=groups.map(([name,keys])=>`<div><span>${name}</span>${keys.map(k=>`<em>${labels[k]} <b>${c[k]||0}</b></em>`).join('')}</div>`).join('')}
function renderLabSummary(){const host=$('#ox-lab-summary');if(!host)return;if(!skill?.available){host.innerHTML='<span>Histórico indisponível</span>';return}const models=modelEntries(),best=(v,l)=>models.map(([k,m])=>({label:m.label,v:m.leads?.[String(l)]?.[v]?.mae})).filter(x=>x.v!=null).sort((a,b)=>a.v-b.v)[0],t=best('tmax',1),p=best('precip',1);host.innerHTML=`<div><span>Melhor Tmax D+1</span><b>${t?t.label:'—'}</b></div><div><span>Melhor chuva D+1</span><b>${p?p.label:'—'}</b></div><div><span>Horizontes</span><b>D+1 → D+7</b></div>`}
function renderWinnerGrid(){const host=$('#ox-winner-grid');if(!host||!skill?.available){if(host)host.innerHTML='<p>Sem histórico suficiente.</p>';return}const variable=$('#ox-winner-variable').value,unit=skillUnit(variable),models=modelEntries(),leads=skill.lead_days||[1,2,3,5,7];host.innerHTML=leads.map(lead=>{const ranks=models.map(([k,m])=>({label:m.label,v:m.leads?.[String(lead)]?.[variable]?.mae,n:m.leads?.[String(lead)]?.[variable]?.samples})).filter(x=>x.v!=null).sort((a,b)=>a.v-b.v),w=ranks[0];return `<div class="ox-winner"><span>D+${lead}</span><b>${w?.label||'—'}</b><small>${w?`MAE ${fmt(w.v,2)} ${unit} · ${w.n||0} dias`:'sem amostra'}</small>${ranks[1]?`<em>2.º ${ranks[1].label} · ${fmt(ranks[1].v,2)}</em>`:''}</div>`}).join('')}
function caseRowsForModel(model){return skill?.models?.[model]?.cases||[]}
function syncCaseDates(){const sel=$('#ox-case-date'),rows=caseRowsForModel($('#ox-case-model').value).filter(r=>Object.keys(r.leads||{}).length),current=sel.value;sel.innerHTML=[...rows].reverse().map(r=>`<option value="${r.date}">${new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(r.date+'T12:00'))}</option>`).join('');if(current&&rows.some(r=>r.date===current))sel.value=current}
function renderForecastCase(){
 const host=$('#ox-case-chart'),stats=$('#ox-case-stats'),note=$('#ox-case-note');if(!skill?.available){host.innerHTML='<p>Sem casos históricos.</p>';return}const model=$('#ox-case-model').value,variable=$('#ox-case-variable').value,day=$('#ox-case-date').value,mod=skill.models?.[model],row=(mod?.cases||[]).find(r=>r.date===day);if(!row){host.innerHTML='<p>Sem previsão individual para esta seleção.</p>';stats.innerHTML='';return}
 const unit=skillUnit(variable),pts=[7,5,3,2,1].map(l=>({label:`D-${l}`,v:row.leads?.[String(l)]?.[variable]})).filter(x=>x.v!=null),observed=row.observed?.[variable];if(observed!=null)pts.push({label:'Observado',v:observed,observed:true});if(pts.length<2){host.innerHTML='<p>Dados insuficientes para mostrar convergência.</p>';return}
 const W=1100,H=390,m={l:72,r:28,t:30,b:55},vals=pts.map(x=>Number(x.v)),a=Math.min(...vals),b=Math.max(...vals),pad=(b-a)*.18||(variable==='precip'?1:2),mn=variable==='precip'?0:a-pad,mx=b+pad,x=i=>m.l+i/(pts.length-1)*(W-m.l-m.r),y=v=>m.t+(mx-v)/(mx-mn||1)*(H-m.t-m.b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=mn+(mx-mn)*i/4,yy=y(v);svg+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-8}" y="${yy+4}" text-anchor="end" font-size="9" fill="#72828b">${fmt(v,1)}</text>`}svg+=`<path d="${pts.map((p,i)=>`${i?'L':'M'} ${x(i)} ${y(Number(p.v))}`).join(' ')}" fill="none" stroke="#2f7d9e" stroke-width="3"/>`;pts.forEach((p,i)=>svg+=`<circle class="ox-case-point" data-label="${p.label}" data-value="${p.v}" cx="${x(i)}" cy="${y(Number(p.v))}" r="${p.observed?7:5}" fill="${p.observed?'#173f50':'#fff'}" stroke="#2f7d9e" stroke-width="3"/><text x="${x(i)}" y="${H-22}" text-anchor="middle" font-size="9" font-weight="${p.observed?900:700}" fill="#60747e">${p.label}</text>`);svg+=`<text x="16" y="${H/2}" transform="rotate(-90 16 ${H/2})" text-anchor="middle" font-size="10" fill="#687a83">${unit}</text></svg>`;host.innerHTML=svg;host.querySelectorAll('.ox-case-point').forEach(el=>{el.addEventListener('mousemove',ev=>skillTip(ev,`<b>${day} · ${el.dataset.label}</b><div>${mod.label}</div><div>${skillLabel(variable)}: <strong>${fmt(el.dataset.value,1)} ${unit}</strong></div>`));el.addEventListener('mouseleave',hideSkillTip)});
 const d7=row.leads?.['7']?.[variable],d1=row.leads?.['1']?.[variable],change=d7!=null&&d1!=null?Number(d1)-Number(d7):null,err=d1!=null&&observed!=null?Number(d1)-Number(observed):null;stats.innerHTML=[['Observado',observed!=null?`${fmt(observed,1)} ${unit}`:'—'],['D-7',d7!=null?`${fmt(d7,1)} ${unit}`:'—'],['D-1',d1!=null?`${fmt(d1,1)} ${unit}`:'—'],['Mudança D-7 → D-1',change!=null?`${change>=0?'+':''}${fmt(change,1)} ${unit}`:'—'],['Erro final D-1',err!=null?`${err>=0?'+':''}${fmt(err,1)} ${unit}`:'—']].map(x=>`<div class="ox-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');note.textContent=`${mod.label} · ${skillLabel(variable)} · ${day}. Mostra a evolução da previsão para o mesmo dia.`;
}
function renderOwnArchive(){const host=$('#ox-own-archive');if(!host)return;if(!verification){host.innerHTML='<p>Arquivo próprio ainda não disponível.</p>';return}const leads=verification.lead_target_hours||[24,48,72,120,168],labels={24:'D+1',48:'D+2',72:'D+3',120:'D+5',168:'D+7'};host.innerHTML=`<p><strong>${verification.archive_records||0}</strong> previsões-alvo guardadas · <strong>${verification.matched_samples||0}</strong> já verificadas.</p><div class="ox-own-leads">${leads.map(l=>`<span>${labels[l]||l+' h'} <b>${verification.summary?.[String(l)]?.samples||0}</b></span>`).join('')}</div><p>Auditoria exata do que Best Match/ECMWF/GFS foram publicados pelo site.</p>`}
function renderSkill(){
 const host=$('#ox-skill-chart'),stats=$('#ox-skill-stats'),note=$('#ox-skill-note');if(!skill?.available){stats.innerHTML='';host.innerHTML='<p style="padding:30px;color:#6d7e86">A análise histórica de previsão está temporariamente indisponível ou ainda a ser gerada.</p>';note.textContent=skill?.stale?'Está a ser usado o último resultado válido quando disponível.':'';renderSkillMonthly();return}
 const variable=$('#ox-skill-variable').value,metric=$('#ox-skill-metric').value,leads=skill.lead_days||[1,2,3,5,7],models=Object.entries(skill.models||{}).filter(([,m])=>m.available);const unit=skillUnit(variable);let vals=[];models.forEach(([,m])=>leads.forEach(l=>{const v=m.leads?.[String(l)]?.[variable]?.[metric];if(v!=null)vals.push(Number(v))}));if(!vals.length){host.innerHTML='<p>Sem valores suficientes para esta seleção.</p>';stats.innerHTML='';return}
 const W=1100,H=430,marg={l:72,r:25,t:28,b:52},minRaw=Math.min(...vals),maxRaw=Math.max(...vals),sym=metric==='bias',bound=sym?Math.max(Math.abs(minRaw),Math.abs(maxRaw),.1):null,ymin=sym?-bound:Math.min(0,minRaw),ymax=sym?bound:maxRaw*1.15||1,x=i=>marg.l+i/(Math.max(1,leads.length-1))*(W-marg.l-marg.r),y=v=>marg.t+(ymax-v)/(ymax-ymin||1)*(H-marg.t-marg.b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=5;i++){const v=ymin+(ymax-ymin)*i/5,yy=y(v);svg+=`<line x1="${marg.l}" y1="${yy}" x2="${W-marg.r}" y2="${yy}" stroke="#e7edef"/><text x="${marg.l-8}" y="${yy+4}" text-anchor="end" font-size="9" fill="#72828b">${fmt(v,2)}</text>`}if(ymin<0&&ymax>0)svg+=`<line x1="${marg.l}" y1="${y(0)}" x2="${W-marg.r}" y2="${y(0)}" stroke="#86969e" stroke-dasharray="4 4"/>`;svg+=`<text x="16" y="${H/2}" transform="rotate(-90 16 ${H/2})" text-anchor="middle" font-size="10" fill="#687a83">${skillMetricLabel(metric)} (${unit})</text>`;leads.forEach((l,i)=>svg+=`<text x="${x(i)}" y="${H-18}" text-anchor="middle" font-size="9" fill="#72828b">D+${l}</text>`);models.forEach(([key,mod],mi)=>{const points=leads.map((l,i)=>({i,l,v:mod.leads?.[String(l)]?.[variable]?.[metric],n:mod.leads?.[String(l)]?.[variable]?.samples})).filter(p=>p.v!=null);if(points.length)svg+=`<path d="${points.map((p,j)=>`${j?'L':'M'} ${x(p.i)} ${y(Number(p.v))}`).join(' ')}" fill="none" stroke="${COLORS[mi]}" stroke-width="2.5"/>`;points.forEach(p=>svg+=`<circle class="ox-skill-point" data-model="${key}" data-lead="${p.l}" data-value="${p.v}" data-n="${p.n||0}" cx="${x(p.i)}" cy="${y(Number(p.v))}" r="5" fill="${COLORS[mi]}"/>`)});svg+=`<text x="${marg.l}" y="15" font-size="9" fill="#687a83">${models.map(([k,m],i)=>`● ${m.label}`).join('   ')}</text></svg>`;host.innerHTML=svg;host.querySelectorAll('.ox-skill-point').forEach(el=>{el.addEventListener('mousemove',ev=>{const mod=skill.models[el.dataset.model];skillTip(ev,`<b>${mod.label} · D+${el.dataset.lead}</b><div>${skillMetricLabel(metric)}: <strong>${fmt(el.dataset.value,2)} ${unit}</strong></div><div>${el.dataset.n} dias comparados</div>`)});el.addEventListener('mouseleave',hideSkillTip)});
 const bestAt=lead=>models.map(([k,m])=>({k,label:m.label,v:m.leads?.[String(lead)]?.[variable]?.mae,n:m.leads?.[String(lead)]?.[variable]?.samples})).filter(x=>x.v!=null).sort((a,b)=>a.v-b.v)[0];const b1=bestAt(1),b3=bestAt(3),b7=bestAt(7);stats.innerHTML=[['Melhor D+1',b1?`${b1.label} · ${fmt(b1.v,2)} ${unit}`:'—'],['Melhor D+3',b3?`${b3.label} · ${fmt(b3.v,2)} ${unit}`:'—'],['Melhor D+7',b7?`${b7.label} · ${fmt(b7.v,2)} ${unit}`:'—'],['Período',`${skill.period_start||'—'} → ${skill.period_end||'—'}`]].map(x=>`<div class="ox-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');note.textContent=`${skillLabel(variable)} · ${skillMetricLabel(metric)}. ${skill.source}. Menor MAE/RMSE é melhor; viés positivo = previsão acima do observado.`;renderSkillMonthly();renderLabSummary();renderWinnerGrid();
}
function renderSkillMonthly(){
 const host=$('#ox-skill-monthly');if(!skill?.available){host.innerHTML='<p style="padding:20px;color:#6d7e86">Sem histórico disponível.</p>';return}const model=$('#ox-skill-model').value,lead=$('#ox-skill-lead').value,variable=$('#ox-skill-variable').value,metric=$('#ox-skill-metric').value,rows=(skill.models?.[model]?.monthly?.[lead]||[]).filter(r=>r[variable]?.[metric]!=null).slice(-24);if(rows.length<2){host.innerHTML='<p>Sem meses suficientes para esta combinação.</p>';return}const vals=rows.map(r=>Number(r[variable][metric])),W=550,H=320,m={l:62,r:18,t:22,b:48},sym=metric==='bias',rawMin=Math.min(...vals),rawMax=Math.max(...vals),bound=sym?Math.max(Math.abs(rawMin),Math.abs(rawMax),.1):null,ymin=sym?-bound:Math.min(0,rawMin),ymax=sym?bound:rawMax*1.15||1,x=i=>m.l+i/(rows.length-1)*(W-m.l-m.r),y=v=>m.t+(ymax-v)/(ymax-ymin||1)*(H-m.t-m.b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=ymin+(ymax-ymin)*i/4,yy=y(v);svg+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,2)}</text>`}svg+=`<path d="${rows.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(Number(r[variable][metric]))}`).join(' ')}" fill="none" stroke="#2f7d9e" stroke-width="2.5"/>`;rows.forEach((r,i)=>{svg+=`<circle class="ox-month-skill" data-month="${r.month}" data-value="${r[variable][metric]}" data-n="${r[variable].samples||0}" cx="${x(i)}" cy="${y(Number(r[variable][metric]))}" r="4" fill="#2f7d9e"/>`;if(i%Math.max(1,Math.ceil(rows.length/8))===0||i===rows.length-1)svg+=`<text x="${x(i)}" y="${H-18}" text-anchor="middle" font-size="8" fill="#72828b">${r.month.slice(2)}</text>`});svg+=`<text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">${skillMetricLabel(metric)} (${skillUnit(variable)})</text></svg>`;host.innerHTML=svg;host.querySelectorAll('.ox-month-skill').forEach(el=>{el.addEventListener('mousemove',ev=>skillTip(ev,`<b>${el.dataset.month} · D+${lead}</b><div>${skill.models[model].label}</div><div>${skillMetricLabel(metric)}: <strong>${fmt(el.dataset.value,2)} ${skillUnit(variable)}</strong></div><div>${el.dataset.n} dias</div>`));el.addEventListener('mouseleave',hideSkillTip)})
}
function renderForecastSkill(){renderLocalModel();renderSkill();syncCaseDates();renderForecastCase();renderOwnArchive();renderLabSummary();renderWinnerGrid();const method=skill?.methodology||{};$('#ox-skill-method').innerHTML=`<p><strong>Arquivo histórico:</strong> ${method.archive||'Open-Meteo Previous Runs.'}</p><p><strong>Casos individuais:</strong> ${method.cases||''}</p><p><strong>Temperatura:</strong> ${method.temperature||''}</p><p><strong>Precipitação:</strong> ${method.precipitation||''}</p><p><strong>Limite:</strong> ${method.caution||''}</p>`;['ox-skill-variable','ox-skill-metric','ox-skill-model','ox-skill-lead'].forEach(id=>{const el=$('#'+id);if(el&&!el.dataset.bound){el.addEventListener('change',renderSkill);el.dataset.bound='1'}});const w=$('#ox-winner-variable');if(w&&!w.dataset.bound){w.addEventListener('change',renderWinnerGrid);w.dataset.bound='1'}const cm=$('#ox-case-model'),cv=$('#ox-case-variable'),cd=$('#ox-case-date');if(cm&&!cm.dataset.bound){cm.addEventListener('change',()=>{syncCaseDates();renderForecastCase()});cm.dataset.bound='1'}if(cv&&!cv.dataset.bound){cv.addEventListener('change',renderForecastCase);cv.dataset.bound='1'}if(cd&&!cd.dataset.bound){cd.addEventListener('change',renderForecastCase);cd.dataset.bound='1'}const lv=$('#ox-local-variable'),vv=$('#ox-local-validation-var');if(lv&&!lv.dataset.bound){lv.addEventListener('change',renderLocalModel);lv.dataset.bound='1'}if(vv&&!vv.dataset.bound){vv.addEventListener('change',renderLocalValidation);vv.dataset.bound='1'}}

function renderWind(){
 const rows=data.wind_sectors||[],W=550,H=330,cx=275,cy=165,R=125,mx=Math.max(1,...rows.map(r=>r.pct));let s=`<svg viewBox="0 0 ${W} ${H}">`;[.25,.5,.75,1].forEach(q=>s+=`<circle cx="${cx}" cy="${cy}" r="${R*q}" fill="none" stroke="#e2eaed"/>`);rows.forEach((r,i)=>{const a=(i*22.5-90)*Math.PI/180,len=R*r.pct/mx,x2=cx+Math.cos(a)*len,y2=cy+Math.sin(a)*len,lx=cx+Math.cos(a)*(R+15),ly=cy+Math.sin(a)*(R+15);s+=`<line x1="${cx}" y1="${cy}" x2="${x2}" y2="${y2}" stroke="#2f7d9e" stroke-width="8" stroke-linecap="round"/><text x="${lx}" y="${ly+3}" text-anchor="middle" font-size="8" fill="#647781">${r.direction}</text>`});s+='</svg>';$('#ox-wind-chart').innerHTML=s;const top=[...rows].sort((a,b)=>b.pct-a.pct).slice(0,3);$('#ox-wind-note').innerHTML=`<p>Esta distribuição usa a <strong>direção dominante de cada dia</strong>, portanto cada dia pesa uma vez. Os setores mais frequentes são ${top.map(x=>`${x.direction} (${fmt(x.pct,1)}%)`).join(', ')}.</p><p>Para frequência por amostras de 1/5 minutos, rajada média e rosa detalhada, use a análise de Vento da Climatologia.</p>`;
}
function renderQuality(){
 const q=data.quality||{},ys=data.quality_years||[];$('#ox-quality-stats').innerHTML=`<div class="ox-stat"><span>Dias válidos</span><b>${q.valid_days||0}</b></div><div class="ox-stat"><span>Dias em falta</span><b>${q.missing_day_count||0}</b></div><div class="ox-stat"><span>Linhas inválidas</span><b>${q.invalid_row_count||0}</b></div><div class="ox-stat"><span>Duplicados</span><b>${q.duplicate_count||0}</b></div>`;barChart($('#ox-quality-chart'),ys,'coverage_pct','Cobertura %');const m=data.methodology||{};$('#ox-method').innerHTML=`<p>${m.scope}</p><p><strong>Correlações:</strong> ${m.correlation}</p><p><strong>Vento:</strong> ${m.wind}</p><p><strong>Tendências:</strong> ${m.trend}</p>`;
}
function show(v){view=v;document.querySelectorAll('.ox-view').forEach(x=>x.hidden=x.id!==`ox-${v}`);document.querySelectorAll('#ox-nav button').forEach(b=>b.classList.toggle('is-active',b.dataset.view===v));if(v==='anomalies'){renderMatrix();renderAnnual();renderMonthProfile()}if(v==='relations')renderRelations();if(v==='extremes')renderExtremes();if(v==='forecast')renderForecastSkill();if(v==='wind')renderWind();if(v==='quality')renderQuality()}
async function init(){[data,skill,verification,localModel]=await Promise.all([getJson('/api/v1/observatory.json'),getJson('/api/v1/forecast-skill.json').catch(()=>({available:false})),getJson('/api/v1/forecast-verification.json').catch(()=>null),getJson('/api/v1/local-model.json').catch(()=>({available:false}))]);$('#ox-series').textContent=`Série ${data.series_start} — ${data.series_end}`;document.querySelectorAll('#ox-nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#ox-matrix-mode').onchange=renderMatrix;$('#ox-annual-mode').onchange=renderAnnual;$('#ox-profile-mode').onchange=renderMonthProfile;const requested=new URLSearchParams(location.search).get('view'),allowed=['anomalies','relations','extremes','forecast','wind','quality'];show(allowed.includes(requested)?requested:'anomalies')}

init();