
const $=q=>document.querySelector(q);
const fmt=(v,d=1)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('pt-PT',{minimumFractionDigits:d,maximumFractionDigits:d});
const COLORS=['#2f7d9e','#c55348','#668e6c','#bd8c2f','#7f6fa0'];
let data=null,skill=null,view='anomalies';
async function getJson(u){const r=await fetch(u+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(r.status);return r.json()}
function tempBg(v){if(v==null)return'';v=Number(v);if(v<=-2)return'#8ebbd0';if(v<-.7)return'#c7dfe9';if(v<.7)return'#eef1df';if(v<2)return'#f1c8a7';return'#dc8073'}
function rainBg(v){if(v==null)return'';v=Number(v);if(v<50)return'#ead7a1';if(v<85)return'#f3e9c9';if(v<115)return'#e5eee6';if(v<160)return'#b7d9e5';return'#70aac2'}
function renderMatrix(){
 const mode=$('#ox-matrix-mode').value,years=[...new Set(data.monthly.map(r=>r.year))],months=[1,2,3,4,5,6,7,8,9,10,11,12],names=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];let s='<table><thead><tr><th>Ano</th>'+names.map(n=>`<th>${n}</th>`).join('')+'</tr></thead><tbody>';
 years.forEach(y=>{s+=`<tr><th>${y}</th>`;months.forEach(m=>{const r=data.monthly.find(x=>x.year===y&&x.month===m),valid=mode==='temp'?r?.temperature_valid:r?.precipitation_valid,val=mode==='temp'?r?.temp_anomaly:r?.precip_pct_normal;if(!r||!valid)s+='<td class="ox-cell invalid">—</td>';else s+=`<td class="ox-cell" title="${r.month_name} ${y}" style="background:${mode==='temp'?tempBg(val):rainBg(val)}">${mode==='temp'?`${val>=0?'+':''}${fmt(val,1)}°`:`${fmt(val,0)}%`}</td>`});s+='</tr>'});s+='</tbody></table>';$('#ox-matrix').innerHTML=s;
}
function lineChart(host,rows,key,unit,color='#2f7d9e'){
 const valid=rows.filter(r=>r[key]!=null),W=550,H=320,m={l:55,r:18,t:20,b:42};if(valid.length<2){host.innerHTML='<p>Dados insuficientes.</p>';return}
 const vals=valid.map(r=>Number(r[key])),mn=Math.min(...vals),mx=Math.max(...vals),pad=(mx-mn)*.12||1,ymin=mn-pad,ymax=mx+pad,x=i=>m.l+i/(valid.length-1)*(W-m.l-m.r),y=v=>m.t+(ymax-v)/(ymax-ymin)*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=ymin+(ymax-ymin)*i/4,yy=y(v);s+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,1)}</text>`}s+=`<path d="${valid.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(Number(r[key]))}`).join(' ')}" fill="none" stroke="${color}" stroke-width="2.6"/>`;valid.forEach((r,i)=>s+=`<circle cx="${x(i)}" cy="${y(Number(r[key]))}" r="4" fill="${color}"><title>${r.year}: ${fmt(r[key],1)} ${unit}</title></circle><text x="${x(i)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.year}</text>`);s+=`<text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">${unit}</text></svg>`;host.innerHTML=s;
}
function renderAnnual(){lineChart($('#ox-annual-chart'),data.annual.filter(r=>r.temperature_valid),'tmean','°C');const t=data.trend||{};$('#ox-trend-note').textContent=`Declive descritivo nos anos completos: ${t.temperature_slope_c_per_year==null?'—':(t.temperature_slope_c_per_year>=0?'+':'')+fmt(t.temperature_slope_c_per_year,3)+' °C/ano'}. ${t.warning||''}`;}
function renderMonthProfile(){
 const rows=data.station_months||[],W=550,H=320,m={l:55,r:18,t:20,b:42},vals=rows.flatMap(r=>[r.station_tmean,r.normal_tmean]).filter(Number.isFinite),mn=Math.min(...vals)-1,mx=Math.max(...vals)+1,x=i=>m.l+i/11*(W-m.l-m.r),y=v=>m.t+(mx-v)/(mx-mn)*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=mn+(mx-mn)*i/4,yy=y(v);s+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,1)}</text>`}const path=k=>rows.filter(r=>r[k]!=null).map((r,i)=>`${i?'L':'M'} ${x(r.month-1)} ${y(Number(r[k]))}`).join(' ');s+=`<path d="${path('normal_tmean')}" fill="none" stroke="#8a999f" stroke-width="2" stroke-dasharray="5 4"/><path d="${path('station_tmean')}" fill="none" stroke="#2f7d9e" stroke-width="2.5"/>`;rows.forEach(r=>s+=`<text x="${x(r.month-1)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.month_name.slice(0,3)}</text>`);s+=`<text x="${m.l}" y="13" font-size="8" fill="#2f7d9e">● estação</text><text x="${m.l+70}" y="13" font-size="8" fill="#7f8e94">┄ normal 1991–2020</text></svg>`;$('#ox-month-profile').innerHTML=s;
}
function corrText(r){const a=Math.abs(Number(r));if(!Number.isFinite(a))return'Sem pares suficientes';const strength=a<.2?'muito fraca':a<.4?'fraca':a<.6?'moderada':a<.8?'forte':'muito forte';return `${strength} · ${r>0?'positiva':'negativa'}`}
function renderRelations(){
 const sel=$('#ox-relation');if(!sel.options.length){sel.innerHTML=data.correlations.map(x=>`<option value="${x.id}">${x.label}</option>`).join('');sel.onchange=renderRelations}
 const rel=data.correlations.find(x=>x.id===sel.value)||data.correlations[0];if(!rel)return;sel.value=rel.id;const pts=data.daily.filter(r=>r[rel.x]!=null&&r[rel.y]!=null),xs=pts.map(r=>Number(r[rel.x])),ys=pts.map(r=>Number(r[rel.y])),W=1100,H=430,m={l:70,r:20,t:20,b:50},xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),x=v=>m.l+(v-xmin)/(xmax-xmin||1)*(W-m.l-m.r),y=v=>m.t+(ymax-v)/(ymax-ymin||1)*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const xv=xmin+(xmax-xmin)*i/4,yv=ymin+(ymax-ymin)*i/4;s+=`<line x1="${m.l}" y1="${y(yv)}" x2="${W-m.r}" y2="${y(yv)}" stroke="#e7edef"/><text x="${m.l-7}" y="${y(yv)+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(yv,1)}</text><text x="${x(xv)}" y="${H-18}" text-anchor="middle" font-size="8" fill="#72828b">${fmt(xv,1)}</text>`}pts.forEach(p=>s+=`<circle cx="${x(Number(p[rel.x]))}" cy="${y(Number(p[rel.y]))}" r="2.5" fill="#2f7d9e" opacity=".42"><title>${p.date}</title></circle>`);s+=`<text x="${W/2}" y="${H-4}" text-anchor="middle" font-size="9" fill="#687a83">${rel.x_unit}</text><text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">${rel.y_unit}</text></svg>`;$('#ox-scatter').innerHTML=s;$('#ox-relation-stats').innerHTML=`<div class="ox-stat"><span>Correlação r</span><b>${fmt(rel.r,3)}</b></div><div class="ox-stat"><span>Leitura</span><b>${corrText(rel.r)}</b></div><div class="ox-stat"><span>Pares de dias</span><b>${pts.length}</b></div><div class="ox-stat"><span>Período</span><b>${data.series_start.slice(0,4)}–${data.series_end.slice(0,4)}</b></div>`;
}
function barChart(host,rows,key,label){
 const valid=rows.filter(r=>r[key]!=null),W=1100,H=350,m={l:55,r:20,t:20,b:42},mx=Math.max(1,...valid.map(r=>Number(r[key]))),bw=(W-m.l-m.r)/Math.max(1,valid.length)*.55,x=i=>m.l+(i+.5)/valid.length*(W-m.l-m.r),y=v=>m.t+(mx-v)/mx*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=mx*i/4,yy=y(v);s+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,0)}</text>`}valid.forEach((r,i)=>{const yy=y(Number(r[key]));s+=`<rect x="${x(i)-bw/2}" y="${yy}" width="${bw}" height="${H-m.b-yy}" rx="4" fill="#2f7d9e"><title>${r.year}: ${fmt(r[key],1)}</title></rect><text x="${x(i)}" y="${H-17}" text-anchor="middle" font-size="8" fill="#72828b">${r.year}${r.complete?'':'*'}</text>`});s+='</svg>';host.innerHTML=s;
}
function renderExtremes(){const key=$('#ox-index').value;barChart($('#ox-index-chart'),data.annual,key,key);$('#ox-index').onchange=renderExtremes}
let oxTip=null;function skillTip(ev,html){if(!oxTip){oxTip=document.createElement('div');oxTip.className='ox-skill-tooltip';document.body.appendChild(oxTip)}oxTip.innerHTML=html;oxTip.style.display='block';let x=ev.clientX+14,y=ev.clientY+14;if(x+oxTip.offsetWidth>innerWidth-10)x=ev.clientX-oxTip.offsetWidth-14;if(y+oxTip.offsetHeight>innerHeight-10)y=ev.clientY-oxTip.offsetHeight-14;oxTip.style.left=x+'px';oxTip.style.top=y+'px'}function hideSkillTip(){if(oxTip)oxTip.style.display='none'}
function skillUnit(v){return v==='precip'?'mm':'°C'}
function skillLabel(v){return {tmax:'T máxima',tmin:'T mínima',tmean:'T média',precip:'Precipitação'}[v]||v}
function skillMetricLabel(m){return {mae:'Erro absoluto médio',bias:'Viés',rmse:'RMSE'}[m]||m}
function renderSkill(){
 const host=$('#ox-skill-chart'),stats=$('#ox-skill-stats'),note=$('#ox-skill-note');if(!skill?.available){stats.innerHTML='';host.innerHTML='<p style="padding:30px;color:#6d7e86">A análise histórica de previsão está temporariamente indisponível ou ainda a ser gerada.</p>';note.textContent=skill?.stale?'Está a ser usado o último resultado válido quando disponível.':'';renderSkillMonthly();return}
 const variable=$('#ox-skill-variable').value,metric=$('#ox-skill-metric').value,leads=skill.lead_days||[1,2,3,5,7],models=Object.entries(skill.models||{}).filter(([,m])=>m.available);const unit=skillUnit(variable);let vals=[];models.forEach(([,m])=>leads.forEach(l=>{const v=m.leads?.[String(l)]?.[variable]?.[metric];if(v!=null)vals.push(Number(v))}));if(!vals.length){host.innerHTML='<p>Sem valores suficientes para esta seleção.</p>';stats.innerHTML='';return}
 const W=1100,H=430,marg={l:72,r:25,t:28,b:52},minRaw=Math.min(...vals),maxRaw=Math.max(...vals),sym=metric==='bias',bound=sym?Math.max(Math.abs(minRaw),Math.abs(maxRaw),.1):null,ymin=sym?-bound:Math.min(0,minRaw),ymax=sym?bound:maxRaw*1.15||1,x=i=>marg.l+i/(Math.max(1,leads.length-1))*(W-marg.l-marg.r),y=v=>marg.t+(ymax-v)/(ymax-ymin||1)*(H-marg.t-marg.b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=5;i++){const v=ymin+(ymax-ymin)*i/5,yy=y(v);svg+=`<line x1="${marg.l}" y1="${yy}" x2="${W-marg.r}" y2="${yy}" stroke="#e7edef"/><text x="${marg.l-8}" y="${yy+4}" text-anchor="end" font-size="9" fill="#72828b">${fmt(v,2)}</text>`}if(ymin<0&&ymax>0)svg+=`<line x1="${marg.l}" y1="${y(0)}" x2="${W-marg.r}" y2="${y(0)}" stroke="#86969e" stroke-dasharray="4 4"/>`;svg+=`<text x="16" y="${H/2}" transform="rotate(-90 16 ${H/2})" text-anchor="middle" font-size="10" fill="#687a83">${skillMetricLabel(metric)} (${unit})</text>`;leads.forEach((l,i)=>svg+=`<text x="${x(i)}" y="${H-18}" text-anchor="middle" font-size="9" fill="#72828b">D+${l}</text>`);models.forEach(([key,mod],mi)=>{const points=leads.map((l,i)=>({i,l,v:mod.leads?.[String(l)]?.[variable]?.[metric],n:mod.leads?.[String(l)]?.[variable]?.samples})).filter(p=>p.v!=null);if(points.length)svg+=`<path d="${points.map((p,j)=>`${j?'L':'M'} ${x(p.i)} ${y(Number(p.v))}`).join(' ')}" fill="none" stroke="${COLORS[mi]}" stroke-width="2.5"/>`;points.forEach(p=>svg+=`<circle class="ox-skill-point" data-model="${key}" data-lead="${p.l}" data-value="${p.v}" data-n="${p.n||0}" cx="${x(p.i)}" cy="${y(Number(p.v))}" r="5" fill="${COLORS[mi]}"/>`)});svg+=`<text x="${marg.l}" y="15" font-size="9" fill="#687a83">${models.map(([k,m],i)=>`● ${m.label}`).join('   ')}</text></svg>`;host.innerHTML=svg;host.querySelectorAll('.ox-skill-point').forEach(el=>{el.addEventListener('mousemove',ev=>{const mod=skill.models[el.dataset.model];skillTip(ev,`<b>${mod.label} · D+${el.dataset.lead}</b><div>${skillMetricLabel(metric)}: <strong>${fmt(el.dataset.value,2)} ${unit}</strong></div><div>${el.dataset.n} dias comparados</div>`)});el.addEventListener('mouseleave',hideSkillTip)});
 const bestAt=lead=>models.map(([k,m])=>({k,label:m.label,v:m.leads?.[String(lead)]?.[variable]?.mae,n:m.leads?.[String(lead)]?.[variable]?.samples})).filter(x=>x.v!=null).sort((a,b)=>a.v-b.v)[0];const b1=bestAt(1),b3=bestAt(3),b7=bestAt(7);stats.innerHTML=[['Melhor D+1',b1?`${b1.label} · ${fmt(b1.v,2)} ${unit}`:'—'],['Melhor D+3',b3?`${b3.label} · ${fmt(b3.v,2)} ${unit}`:'—'],['Melhor D+7',b7?`${b7.label} · ${fmt(b7.v,2)} ${unit}`:'—'],['Período',`${skill.period_start||'—'} → ${skill.period_end||'—'}`]].map(x=>`<div class="ox-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');note.textContent=`${skillLabel(variable)} · ${skillMetricLabel(metric)}. ${skill.source}. Menor MAE/RMSE é melhor; viés positivo = previsão acima do observado.`;renderSkillMonthly();
}
function renderSkillMonthly(){
 const host=$('#ox-skill-monthly');if(!skill?.available){host.innerHTML='<p style="padding:20px;color:#6d7e86">Sem histórico disponível.</p>';return}const model=$('#ox-skill-model').value,lead=$('#ox-skill-lead').value,variable=$('#ox-skill-variable').value,metric=$('#ox-skill-metric').value,rows=(skill.models?.[model]?.monthly?.[lead]||[]).filter(r=>r[variable]?.[metric]!=null).slice(-24);if(rows.length<2){host.innerHTML='<p>Sem meses suficientes para esta combinação.</p>';return}const vals=rows.map(r=>Number(r[variable][metric])),W=550,H=320,m={l:62,r:18,t:22,b:48},sym=metric==='bias',rawMin=Math.min(...vals),rawMax=Math.max(...vals),bound=sym?Math.max(Math.abs(rawMin),Math.abs(rawMax),.1):null,ymin=sym?-bound:Math.min(0,rawMin),ymax=sym?bound:rawMax*1.15||1,x=i=>m.l+i/(rows.length-1)*(W-m.l-m.r),y=v=>m.t+(ymax-v)/(ymax-ymin||1)*(H-m.t-m.b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<=4;i++){const v=ymin+(ymax-ymin)*i/4,yy=y(v);svg+=`<line x1="${m.l}" y1="${yy}" x2="${W-m.r}" y2="${yy}" stroke="#e7edef"/><text x="${m.l-7}" y="${yy+4}" text-anchor="end" font-size="8" fill="#72828b">${fmt(v,2)}</text>`}svg+=`<path d="${rows.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(Number(r[variable][metric]))}`).join(' ')}" fill="none" stroke="#2f7d9e" stroke-width="2.5"/>`;rows.forEach((r,i)=>{svg+=`<circle class="ox-month-skill" data-month="${r.month}" data-value="${r[variable][metric]}" data-n="${r[variable].samples||0}" cx="${x(i)}" cy="${y(Number(r[variable][metric]))}" r="4" fill="#2f7d9e"/>`;if(i%Math.max(1,Math.ceil(rows.length/8))===0||i===rows.length-1)svg+=`<text x="${x(i)}" y="${H-18}" text-anchor="middle" font-size="8" fill="#72828b">${r.month.slice(2)}</text>`});svg+=`<text x="15" y="${H/2}" transform="rotate(-90 15 ${H/2})" text-anchor="middle" font-size="9" fill="#687a83">${skillMetricLabel(metric)} (${skillUnit(variable)})</text></svg>`;host.innerHTML=svg;host.querySelectorAll('.ox-month-skill').forEach(el=>{el.addEventListener('mousemove',ev=>skillTip(ev,`<b>${el.dataset.month} · D+${lead}</b><div>${skill.models[model].label}</div><div>${skillMetricLabel(metric)}: <strong>${fmt(el.dataset.value,2)} ${skillUnit(variable)}</strong></div><div>${el.dataset.n} dias</div>`));el.addEventListener('mouseleave',hideSkillTip)})
}
function renderForecastSkill(){renderSkill();const method=skill?.methodology||{};$('#ox-skill-method').innerHTML=`<p><strong>Arquivo:</strong> ${method.archive||'Open-Meteo Previous Runs.'}</p><p><strong>Temperatura:</strong> ${method.temperature||''}</p><p><strong>Precipitação:</strong> ${method.precipitation||''}</p><p><strong>Limite:</strong> ${method.caution||''}</p>`;['ox-skill-variable','ox-skill-metric','ox-skill-model','ox-skill-lead'].forEach(id=>{const el=$('#'+id);if(el&&!el.dataset.bound){el.addEventListener('change',renderSkill);el.dataset.bound='1'}})}
function renderWind(){
 const rows=data.wind_sectors||[],W=550,H=330,cx=275,cy=165,R=125,mx=Math.max(1,...rows.map(r=>r.pct));let s=`<svg viewBox="0 0 ${W} ${H}">`;[.25,.5,.75,1].forEach(q=>s+=`<circle cx="${cx}" cy="${cy}" r="${R*q}" fill="none" stroke="#e2eaed"/>`);rows.forEach((r,i)=>{const a=(i*22.5-90)*Math.PI/180,len=R*r.pct/mx,x2=cx+Math.cos(a)*len,y2=cy+Math.sin(a)*len,lx=cx+Math.cos(a)*(R+15),ly=cy+Math.sin(a)*(R+15);s+=`<line x1="${cx}" y1="${cy}" x2="${x2}" y2="${y2}" stroke="#2f7d9e" stroke-width="8" stroke-linecap="round"/><text x="${lx}" y="${ly+3}" text-anchor="middle" font-size="8" fill="#647781">${r.direction}</text>`});s+='</svg>';$('#ox-wind-chart').innerHTML=s;const top=[...rows].sort((a,b)=>b.pct-a.pct).slice(0,3);$('#ox-wind-note').innerHTML=`<p>Esta distribuição usa a <strong>direção dominante de cada dia</strong>, portanto cada dia pesa uma vez. Os setores mais frequentes são ${top.map(x=>`${x.direction} (${fmt(x.pct,1)}%)`).join(', ')}.</p><p>Para frequência por amostras de 1/5 minutos, rajada média e rosa detalhada, use a análise de Vento da Climatologia.</p>`;
}
function renderQuality(){
 const q=data.quality||{},ys=data.quality_years||[];$('#ox-quality-stats').innerHTML=`<div class="ox-stat"><span>Dias válidos</span><b>${q.valid_days||0}</b></div><div class="ox-stat"><span>Dias em falta</span><b>${q.missing_day_count||0}</b></div><div class="ox-stat"><span>Linhas inválidas</span><b>${q.invalid_row_count||0}</b></div><div class="ox-stat"><span>Duplicados</span><b>${q.duplicate_count||0}</b></div>`;barChart($('#ox-quality-chart'),ys,'coverage_pct','Cobertura %');const m=data.methodology||{};$('#ox-method').innerHTML=`<p>${m.scope}</p><p><strong>Correlações:</strong> ${m.correlation}</p><p><strong>Vento:</strong> ${m.wind}</p><p><strong>Tendências:</strong> ${m.trend}</p>`;
}
function show(v){view=v;document.querySelectorAll('.ox-view').forEach(x=>x.hidden=x.id!==`ox-${v}`);document.querySelectorAll('#ox-nav button').forEach(b=>b.classList.toggle('is-active',b.dataset.view===v));if(v==='anomalies'){renderMatrix();renderAnnual();renderMonthProfile()}if(v==='relations')renderRelations();if(v==='extremes')renderExtremes();if(v==='forecast')renderForecastSkill();if(v==='wind')renderWind();if(v==='quality')renderQuality()}
async function init(){[data,skill]=await Promise.all([getJson('/api/v1/observatory.json'),getJson('/api/v1/forecast-skill.json').catch(()=>({available:false}))]);$('#ox-series').textContent=`Série ${data.series_start} — ${data.series_end}`;document.querySelectorAll('#ox-nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#ox-matrix-mode').onchange=renderMatrix;show('anomalies')}
init();