const $=q=>document.querySelector(q);
const fmt=(v,d=1)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('pt-PT',{minimumFractionDigits:d,maximumFractionDigits:d});
const dateText=s=>{if(!s)return'';const d=new Date(s+'T12:00:00');return new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'short',year:'numeric'}).format(d)};
function icon(n){const c='viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"';const x={temp:`<svg ${c}><path d="M14 14.8V5a4 4 0 0 0-8 0v9.8a6 6 0 1 0 8 0Z"/><path d="M10 11v5"/></svg>`,rain:`<svg ${c}><path d="M7 16a4 4 0 1 1 1-7.9A5.5 5.5 0 0 1 18.5 10 3.5 3.5 0 0 1 18 17H8"/><path d="m8 19-1 2m5-2-1 2m5-2-1 2"/></svg>`,wind:`<svg ${c}><path d="M3 8h11c3 0 3-4 0-4-1.5 0-2.2.8-2.5 1.5M3 12h16c3 0 3 4 0 4-1.5 0-2.2-.8-2.5-1.5M3 16h7"/></svg>`,press:`<svg ${c}><circle cx="12" cy="12" r="8"/><path d="m12 12 4-3M8 18h8"/></svg>`,sun:`<svg ${c}><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5M17.5 17.5 19 19M5 19l1.5-1.5M17.5 6.5 19 5"/></svg>`,streak:`<svg ${c}><path d="M4 7h6M4 12h10M4 17h16"/><circle cx="17" cy="7" r="3"/></svg>`};return x[n]||x.temp}
const CATS={temperature:['Temperatura','temp'],precipitation:['Precipitação','rain'],wind:['Vento','wind'],atmosphere:['Atmosfera','press'],solar_agro:['Solar / agro','sun'],persistence:['Persistência','streak']};
let data=null,category='temperature';
async function getJson(u){const r=await fetch(u+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(r.status);return r.json()}
function digitsFor(r){if(r.unit==='%'||r.unit==='W/m²'||r.unit==='dias'||r.unit==='noites')return 0;if(r.unit==='mm')return r.label?.includes('evapotrans')?2:1;return 1}
function valueText(r){return `${fmt(r.value,digitsFor(r))}${r.unit?` ${r.unit}`:''}`}
function whenText(r){if(r.date)return dateText(r.date);if(r.start&&r.end)return `${dateText(r.start)} — ${dateText(r.end)}`;if(r.month_name&&r.year)return `${r.month_name} ${r.year}`;if(r.month&&r.year)return `${String(r.month).padStart(2,'0')}/${r.year}`;if(r.year)return String(r.year);if(r.period_start&&r.period_end)return `${dateText(r.period_start)} — ${dateText(r.period_end)}`;return''}
function card(r){if(!r)return'';const derived=String(r.source||'').toLowerCase().includes('derivad');return `<article class="rx-record"><em class="badge ${derived?'derived':''}">${derived?'derivado':'Cumulus'}</em><span>${r.label}</span><b>${valueText(r)}</b><small>${whenText(r)}${r.note?`<br>${r.note}`:''}</small></article>`}
function renderFeatured(){const c=data.categories||{},pick=[[c.temperature?.[0],'temp'],[c.temperature?.[1],'temp'],[c.precipitation?.[0],'rain'],[c.persistence?.[0],'streak'],[c.wind?.[0],'wind'],[c.solar_agro?.[1],'sun']];$('#rx-featured').innerHTML=pick.filter(x=>x[0]).map(([r,ic])=>`<article class="rx-feature"><div class="ico">${icon(ic)}</div><span>${r.label}</span><b>${valueText(r)}</b><small>${whenText(r)}</small></article>`).join('')}
function renderCategory(){const [label]=CATS[category];$('#rx-category-title').textContent=label;$('#rx-record-grid').innerHTML=(data.categories?.[category]||[]).map(card).join('')||'<p>Sem dados para esta categoria.</p>';document.querySelectorAll('.rx-category').forEach(b=>b.classList.toggle('is-active',b.dataset.cat===category))}
function renderMonth(){const row=data.by_calendar_month?.[$('#rx-month').value];$('#rx-month-grid').innerHTML=(row?.records||[]).map(card).join('')||'<p>Sem recordes para este mês.</p>'}
function renderPeriodRecords(){const k=$('#rx-period-kind').value;$('#rx-period-grid').innerHTML=(data.period_records?.[k]||[]).map(card).join('')}
function renderRankings(){const r=data.rankings?.[$('#rx-ranking').value],items=r?.items||[];$('#rx-ranking-list').innerHTML=items.map((x,i)=>`<div class="rx-rank"><div class="rx-rank-num">${i+1}</div><div class="rx-rank-date">${dateText(x.date)}</div><div class="rx-rank-value">${fmt(x.value,x.unit==='%'?0:1)}${x.unit?` ${x.unit}`:''}</div></div>`).join('')}
function renderStreaks(){const s=data.streaks||{},w=data.waves||{},rows=[['Sem chuva',s.dry?.max_streak_days,'dias',s.dry?.max_streak_start,s.dry?.max_streak_end],['Com chuva',s.wet?.max_streak_days,'dias',s.wet?.max_streak_start,s.wet?.max_streak_end],['Tmax ≥30 °C',s.hot30?.max_streak_days,'dias',s.hot30?.max_streak_start,s.hot30?.max_streak_end],['Tmax >35 °C',s.hot35?.max_streak_days,'dias',s.hot35?.max_streak_start,s.hot35?.max_streak_end],['Noites tropicais',s.tropical?.max_streak_days,'noites',s.tropical?.max_streak_start,s.tropical?.max_streak_end],['Geadas',s.frost?.max_streak_days,'dias',s.frost?.max_streak_start,s.frost?.max_streak_end],['Onda de calor',w.longest_heatwave?.days,'dias',w.longest_heatwave?.start,w.longest_heatwave?.end],['Onda de frio',w.longest_coldwave?.days,'dias',w.longest_coldwave?.start,w.longest_coldwave?.end]];$('#rx-streaks').innerHTML=rows.filter(x=>x[1]!=null).map(x=>`<div class="rx-streak"><span>${x[0]}</span><b>${x[1]} ${x[2]}<br><small>${x[3]?`${dateText(x[3])} — ${dateText(x[4])}`:''}</small></b></div>`).join('')}
function renderRecent(){const r=data.recent_records||[],panel=$('#rx-recent-panel');if(!r.length){panel.style.display='none';return}panel.style.display='block';$('#rx-recent').innerHTML=r.map(x=>`<div class="rx-recent-item"><b>${x.label}</b><span>${x.category} · ${valueText(x)} · ${whenText(x)}</span></div>`).join('')}
function initControls(){$('#rx-categories').innerHTML=Object.entries(CATS).map(([k,[l,ic]])=>`<button class="rx-category" data-cat="${k}" type="button">${icon(ic)} ${l}</button>`).join('');document.querySelectorAll('.rx-category').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderCategory()});const months=data.by_calendar_month||{};$('#rx-month').innerHTML=Object.keys(months).sort((a,b)=>Number(a)-Number(b)).map(k=>`<option value="${k}">${months[k].month_name}</option>`).join('');$('#rx-month').value=String(new Date().getMonth()+1);if(!$('#rx-month').value)$('#rx-month').selectedIndex=0;$('#rx-month').onchange=renderMonth;$('#rx-period-kind').onchange=renderPeriodRecords;$('#rx-ranking').innerHTML=Object.entries(data.rankings||{}).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('');$('#rx-ranking').onchange=renderRankings}
async function init(){try{data=await getJson('/api/v1/records.json');const m=data.metadata||{};$('#rx-period').textContent=`Série ${dateText(m.series_start)} — ${dateText(m.series_end)}`;initControls();renderFeatured();renderCategory();renderMonth();renderPeriodRecords();renderRankings();renderStreaks();renderRecent();$('#rx-quality').innerHTML=`<p>${m.quality_note||''}</p><p><strong>Recordes derivados</strong> são métricas úteis calculadas pelo Climate Analyzer a partir dos dados do Cumulus: amplitudes térmicas, janelas móveis de precipitação e sequências consecutivas. Não são apresentados como recordes nativos do Cumulus.</p><p>Nas sequências secas/chuvosas, o limiar é <code>${fmt(m.rain_day_threshold_mm,1)} mm/dia</code>. Dias em falta interrompem a sequência.</p>`}catch(e){console.error(e);document.body.insertAdjacentHTML('beforeend','<p style="padding:20px">Não foi possível carregar os recordes.</p>')}}
init();